---
abstract: 'persistent application data storage'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  File::Temp: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
keywords:
  - application
  - data
  - storage
  - persistant
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Stash
provides:
  App::Stash:
    file: lib/App/Stash.pm
    version: 0.02
requires:
  Class::Accessor::Chained::Fast: 0
  File::HomeDir: 0
  File::Path: 0
  JSON::Util: 0
  Path::Class: 0
resources:
  bugtracker: http://github.com/jozef/App-Stash/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jozef/App-Stash.git
version: 0.02
